#!/usr/bin/env bash
set -Eeuo pipefail

RUNTIME_DIR="${1:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../runtime" && pwd)}"

if [ ! -d "$RUNTIME_DIR" ]; then
  printf 'Runtime directory does not exist: %s\n' "$RUNTIME_DIR" >&2
  exit 1
fi

# Only remove stale media artifacts after 4 hours. Active jobs and user
# thumbnails are intentionally left alone. Run when no large batch is active.
find "$RUNTIME_DIR" -maxdepth 1 -type f -mmin +240 \
  \( -name '*.mp4' -o -name '*.mp3' -o -name '*.m4a' -o -name '*.mkv' \
     -o -name '*.avi' -o -name '*.mov' -o -name '*.webm' -o -name '*.part*' \
     -o -name '*.temp' \) \
  -print -delete

if [ -d "$RUNTIME_DIR/downloads" ]; then
  find "$RUNTIME_DIR/downloads" -type f -mmin +240 -print -delete
fi

# ffmpeg screenshots generated by the upstream code use an ISO date prefix;
# numeric Telegram user thumbnails do not match this pattern.
find "$RUNTIME_DIR" -maxdepth 1 -type f -mmin +10080 \
  -name '20??-??-??_*.jpg' -print -delete

if [ -d "$RUNTIME_DIR/tmp" ]; then
  find "$RUNTIME_DIR/tmp" -type f -mmin +1440 -print -delete
fi
